version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    restart: always
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq  

  tweet-collector:
    build:
      context: tweet-collector/
    environment:
      - QUEUE_NAME=$QUEUE_NAME
      - RABBITMQ_URL=$RABBITMQ_URL
      - TWITTER_BASE_URL=$TWITTER_BASE_URL
      - BEARER_TOKEN=$BEARER_TOKEN
    container_name: tweet-collector  
    restart: always 
    volumes: 
      - ./dist/:/usr/src/tweet-collector/dist/:z
      - ./package.json:/usr/src/tweet-collector/package.json:z
    depends_on:
      - rabbitmq   
    links: 
      - rabbitmq
